// Path parameter converters for generated code.
package runtime

import (
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"
)

// ---------------------------------------------------------------------------
// Path parameter converters
// ---------------------------------------------------------------------------

// Path param converters. These are called by code generated by
// protoc-gen-zararpc to extract typed values from string path
// parameters, mirroring grpc-gateway's runtime package.

// PathString converts a path param value to a string (identity).
func PathString(val string) (string, error) {
	return val, nil
}

// PathBool converts a path param value to a bool.
func PathBool(val string) (bool, error) {
	b, err := strconv.ParseBool(val)
	if err != nil {
		return false, fmt.Errorf("parse %q as bool: %w", val, err)
	}
	return b, nil
}

// PathInt32 converts a path param value to an int32.
func PathInt32(val string) (int32, error) {
	n, err := strconv.ParseInt(val, 10, 32)
	if err != nil {
		return 0, fmt.Errorf("parse %q as int32: %w", val, err)
	}
	return int32(n), nil
}

// PathInt64 converts a path param value to an int64.
func PathInt64(val string) (int64, error) {
	n, err := strconv.ParseInt(val, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("parse %q as int64: %w", val, err)
	}
	return n, nil
}

// PathUint32 converts a path param value to a uint32.
func PathUint32(val string) (uint32, error) {
	n, err := strconv.ParseUint(val, 10, 32)
	if err != nil {
		return 0, fmt.Errorf("parse %q as uint32: %w", val, err)
	}
	return uint32(n), nil
}

// PathUint64 converts a path param value to a uint64.
func PathUint64(val string) (uint64, error) {
	n, err := strconv.ParseUint(val, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("parse %q as uint64: %w", val, err)
	}
	return n, nil
}

// PathFloat32 converts a path param value to a float32.
func PathFloat32(val string) (float32, error) {
	n, err := strconv.ParseFloat(val, 32)
	if err != nil {
		return 0, fmt.Errorf("parse %q as float32: %w", val, err)
	}
	return float32(n), nil
}

// PathFloat64 converts a path param value to a float64.
func PathFloat64(val string) (float64, error) {
	n, err := strconv.ParseFloat(val, 64)
	if err != nil {
		return 0, fmt.Errorf("parse %q as float64: %w", val, err)
	}
	return n, nil
}

// PathBytes converts a base64-encoded path param value to a byte slice.
func PathBytes(val string) ([]byte, error) {
	b, err := base64.RawURLEncoding.DecodeString(val)
	if err != nil {
		b, err = base64.StdEncoding.DecodeString(val)
		if err != nil {
			return nil, fmt.Errorf("decode %q as base64: %w", val, err)
		}
	}
	return b, nil
}

// PathStringSlice converts a comma-separated path param value to a string
// slice. For example, "a,b,c" becomes ["a", "b", "c"].
func PathStringSlice(val string) ([]string, error) {
	return strings.Split(val, ","), nil
}

// PathInt64Slice converts a comma-separated path param value to an int64
// slice.
func PathInt64Slice(val string) ([]int64, error) {
	parts := strings.Split(val, ",")
	result := make([]int64, 0, len(parts))
	for _, p := range parts {
		n, err := strconv.ParseInt(strings.TrimSpace(p), 10, 64)
		if err != nil {
			return nil, fmt.Errorf("parse %q as int64: %w", p, err)
		}
		result = append(result, n)
	}
	return result, nil
}
