// Package kernel holds the operation machinery: Operation, OperationBuilder,
// Service registry, the HTTP Handler adapter, and the server lifecycle.
package kernel

import (
	"net/http"
	"reflect"

	"github.com/aldok10/zara-rpc/codes"
	"github.com/aldok10/zara-rpc/encoding"
	"github.com/aldok10/zara-rpc/middleware"
	"github.com/aldok10/zara-rpc/peer"
	"github.com/aldok10/zara-rpc/runtime"
	"github.com/aldok10/zara-rpc/status"
)

// Operation defines a single HTTP operation that maps to an RPC operation,
// in the style of grpc-gateway's google.api.http annotations. It is
// created with the generic NewOperation constructor, which captures the
// request and response types.
type Operation struct {
	// Method is the HTTP method: GET, POST, PUT, DELETE, PATCH, or a
	// custom verb via the path template suffix (e.g. ":custom").
	Method string
	// Path is the path template, e.g. "/v1/users/{id}" or
	// "/v1/{name=messages/*}".
	Path string
	// Procedure is the fully-qualified procedure name, e.g.
	// "/acme.users.v1.UsersService/GetUser". If empty, it is derived
	// from the service name and the operation's RPC name.
	Procedure string
	// RPC is the RPC method name, e.g. "GetUser". Used to derive the
	// procedure name when Procedure is empty.
	RPC string
	// Body specifies the body mapping:
	//   "*"        - the entire request body decodes into the request message
	//   "field"    - only the named field is decoded from the body
	//   ""         - no body; all unbound fields come from query params
	Body string
	// ResponseBody specifies a field of the response message to use as
	// the response body. Empty means the whole response message.
	ResponseBody string

	codec              encoding.Codec
	interceptors       []middleware.UnaryInterceptor
	streamInterceptors []middleware.StreamInterceptor
	unary              middleware.UnaryFunc
	serverStream       serverStreamFunc
	clientStream       clientStreamFunc
	bidiStream         bidiStreamFunc
	newRequest         func(ctx runtime.Ctx, r *http.Request, params map[string]string, codec encoding.Codec) (runtime.AnyRequest, error)
	requestBuilder     RequestBuilder
	reqType            reflect.Type
	resType            reflect.Type
	streamType         runtime.StreamType
	// specCache is the operation Spec, computed once after the options are
	// applied. The hot path reads it instead of reconstructing the Spec
	// (and its "/"+RPC string concatenation) per request.
	specCache runtime.Spec
}

// serverStreamFunc is the non-generic form of a server-streaming Operation.
type serverStreamFunc func(ctx runtime.Ctx, req runtime.AnyRequest, stream runtime.ServerStream[any]) error

// clientStreamFunc is the non-generic form of a client-streaming Operation.
type clientStreamFunc func(ctx runtime.Ctx, stream runtime.ClientStream[any]) (runtime.AnyResponse, error)

// bidiStreamFunc is the non-generic form of a bidi-streaming Operation.
type bidiStreamFunc func(ctx runtime.Ctx, stream runtime.BidiStream[any, any]) error

// ServerStreamFunc handles a server-streaming RPC: one request, many
// responses. Responses are written to the stream as SSE events.
type ServerStreamFunc[Req, Res any] func(ctx runtime.Ctx, req *runtime.Request[Req], stream runtime.ServerStream[Res]) error

// ClientStreamFunc handles a client-streaming RPC: many requests, one
// response. Requests are read from the stream as newline-delimited JSON.
type ClientStreamFunc[Req, Res any] func(ctx runtime.Ctx, stream runtime.ClientStream[Req]) (*runtime.Response[Res], error)

// BidiStreamFunc handles a bidi-streaming RPC: many requests, many
// responses, transported over a WebSocket.
type BidiStreamFunc[Req, Res any] func(ctx runtime.Ctx, stream runtime.BidiStream[Req, Res]) error

// RequestBuilder builds a typed request from an HTTP request and path
// params. It is used by code generated by protoc-gen-zararpc to perform
// type-safe path parameter extraction for protobuf messages. ctx carries
// the request metadata (Ctx.Meta); it is passed separately so the hot path
// does not need to re-wrap the request with r.WithContext.
type RequestBuilder func(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error)

// spec returns the cached operation Spec, computed once after the options
// are applied.
func (e *Operation) spec() runtime.Spec {
	return e.specCache
}

// computeSpec builds the Spec from the operation's fields. Called once
// during construction, after the options are applied.
func computeSpec(e *Operation) runtime.Spec {
	procedure := e.Procedure
	if procedure == "" {
		procedure = "/" + e.RPC
	}
	return runtime.Spec{
		Procedure: procedure,
		Method:    e.Method,
		Path:      e.Path,
		RPC:       e.RPC,
	}
}

// NewOperation creates a typed operation. The Operation receives a
// *runtime.Request[Req] with path params, query params, and body already
// populated according to the operation's Body mapping, and returns a
// *runtime.Response[Res].
func NewOperation[Req, Res any](
	method, path string,
	handler func(runtime.Ctx, *runtime.Request[Req]) (*runtime.Response[Res], error),
	opts ...OperationOption,
) *Operation {
	var op Operation
	b := (*OperationBuilder[Req, Res])(&op)
	b.SetMethod(method).SetPath(path).SetUnaryHandler(handler)
	for _, opt := range opts {
		opt((*Operation)(b))
	}
	return b.Build()
}

// NewServerStreamOperation creates a server-streaming operation. The
// Operation receives the typed request and a stream it sends responses on;
// each response is written as an SSE event.
func NewServerStreamOperation[Req, Res any](
	method, path string,
	handler ServerStreamFunc[Req, Res],
	opts ...OperationOption,
) *Operation {
	var op Operation
	b := (*OperationBuilder[Req, Res])(&op)
	b.SetMethod(method).SetPath(path).SetServerStreamHandler(handler)
	for _, opt := range opts {
		opt((*Operation)(b))
	}
	return b.Build()
}

// NewClientStreamOperation creates a client-streaming operation. The
// Operation receives a stream of requests (newline-delimited JSON in the
// request body) and returns a single response.
func NewClientStreamOperation[Req, Res any](
	method, path string,
	handler ClientStreamFunc[Req, Res],
	opts ...OperationOption,
) *Operation {
	var op Operation
	b := (*OperationBuilder[Req, Res])(&op)
	b.SetMethod(method).SetPath(path).SetClientStreamHandler(handler)
	for _, opt := range opts {
		opt((*Operation)(b))
	}
	return b.Build()
}

// NewBidiStreamOperation creates a bidi-streaming operation, transported
// over a WebSocket. The Operation receives a stream it both reads requests
// from and writes responses to.
func NewBidiStreamOperation[Req, Res any](
	method, path string,
	handler BidiStreamFunc[Req, Res],
	opts ...OperationOption,
) *Operation {
	var op Operation
	b := (*OperationBuilder[Req, Res])(&op)
	b.SetMethod(method).SetPath(path).SetBidiStreamHandler(handler)
	for _, opt := range opts {
		opt((*Operation)(b))
	}
	return b.Build()
}

// rawRequest adapts a decoded message to runtime.AnyRequest for WebSocket
// transports where there is no HTTP request to build a typed Request from.
type rawRequest struct {
	msg    any
	spec   runtime.Spec
	peer   peer.Peer
	header http.Header
}

func (r *rawRequest) Any() any            { return r.msg }
func (r *rawRequest) Spec() runtime.Spec  { return r.spec }
func (r *rawRequest) Peer() peer.Peer     { return r.peer }
func (r *rawRequest) Header() http.Header { return r.header }

// decodeRequest builds a request message from raw codec bytes. It is used
// by WebSocket transports where the request arrives as the first frame
// instead of an HTTP request body.
func (e *Operation) decodeRequest(data []byte, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := reflect.New(e.reqType).Interface()
	if err := codec.Unmarshal(data, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request: %v", err)
	}
	return &rawRequest{
		msg:    msg,
		spec:   e.spec(),
		peer:   peer.Peer{Protocol: "websocket"},
		header: make(http.Header),
	}, nil
}
