// REST-to-gRPC gateway emission.
package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

// ---------------------------------------------------------------------------
// Gateway generation (REST -> gRPC proxy, mirroring grpc-gateway's .pb.gw.go)
// ---------------------------------------------------------------------------

// generateGatewayFile emits the REST-to-gRPC gateway adapter for a proto
// file: a handler that implements the zararpc HTTP contract by delegating
// every method to the grpc-go client, plus a Register*Gateway helper.
func generateGatewayFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + ".gateway.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-zararpc. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-zararpc v0.1.0")
	g.P("// - protoc ", protocVersion(gen))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, svc := range file.Services {
		generateGatewayService(g, svc)
	}
}

// generateGatewayService emits the gateway adapter for one service.
func generateGatewayService(g *protogen.GeneratedFile, svc *protogen.Service) {
	svcName := svc.GoName
	ctxType := q(g, runtimeImport, "Ctx")
	grpcConn := q(g, grpcImport, "ClientConn")
	adapter := "gateway" + svcName
	clientName := svcName + "Client" // grpc-go client, same package

	g.P("// ", adapter, " adapts the grpc-go client to the zararpc HTTP handler")
	g.P("// contract. It is used by Register", svcName, "Gateway.")
	g.P("type ", adapter, " struct {")
	g.P("Unimplemented", svcName, "Handler")
	g.P("client ", clientName)
	g.P("}")
	g.P()

	for _, method := range svc.Methods {
		generateGatewayMethod(g, svc, method, adapter, ctxType)
	}

	g.P("// Register", svcName, "Gateway registers REST routes on mux that proxy")
	g.P("// every call to the gRPC server reachable through conn.")
	g.P("func Register", svcName, "Gateway(mux *", sym(g, "Mux"), ", conn *", grpcConn, ") error {")
	g.P("svc := &", adapter, "{client: New", clientName, "(conn)}")
	g.P("return Register", svcName, "Routes(mux, svc)")
	g.P("}")
	g.P()
}

// generateGatewayMethod emits one handler method on the gateway adapter.
func generateGatewayMethod(g *protogen.GeneratedFile, svc *protogen.Service, method *protogen.Method, adapter, ctxType string) {
	recv := "(g *" + adapter + ")"
	inType := g.QualifiedGoIdent(method.Input.GoIdent)
	outType := g.QualifiedGoIdent(method.Output.GoIdent)
	mode := streamMode(method)

	// forwardHeaders copies zararpc request headers into outgoing gRPC
	// metadata so auth data (e.g. Authorization) survives the gateway hop.
	// Hop-by-hop headers are skipped by metadata.HeaderPairsFromMeta; the
	// guard avoids a pointless AppendToOutgoingContext (which wraps the
	// context even with zero pairs). gctx is the plain context.Context
	// extracted from the runtime.Ctx — the grpc-go client needs it, not
	// the Ctx.
	forwardHeaders := func() {
		g.P("gctx := ctx.Context()")
		g.P("if pairs := ", sym(g, "HeaderPairsFromMeta"), "(ctx.Meta()); len(pairs) > 0 {")
		g.P("gctx = ", q(g, grpcMetadataImport, "AppendToOutgoingContext"), "(gctx, pairs...)")
		g.P("}")
	}
	// toZaraError converts a grpc status error to a zararpc error so error
	// codes and HTTP status codes survive the gateway hop.
	toZaraError := func() string {
		return sym(g, "FromGRPCStatus") + "(err)"
	}

	switch mode {
	case "server":
		ioEOF := q(g, ioImport, "EOF")
		g.P("func ", recv, " ", method.GoName, "(ctx ", ctxType, ", req *", inType, ", stream ", sym(g, "ServerStream"), "[*", outType, "]) error {")
		forwardHeaders()
		g.P("clientStream, err := g.client.", method.GoName, "(gctx, req)")
		g.P("if err != nil {")
		g.P("return ", toZaraError())
		g.P("}")
		g.P("for {")
		g.P("msg, err := clientStream.Recv()")
		g.P("if err == ", ioEOF, " {")
		g.P("return nil")
		g.P("}")
		g.P("if err != nil {")
		g.P("return ", toZaraError())
		g.P("}")
		g.P("if err := stream.Send(msg); err != nil {")
		g.P("return err")
		g.P("}")
		g.P("}")
		g.P("}")
		g.P()

	case "client":
		ioEOF := q(g, ioImport, "EOF")
		g.P("func ", recv, " ", method.GoName, "(ctx ", ctxType, ", stream ", sym(g, "ClientStream"), "[*", inType, "]) (*", outType, ", error) {")
		forwardHeaders()
		g.P("clientStream, err := g.client.", method.GoName, "(gctx)")
		g.P("if err != nil {")
		g.P("return nil, ", toZaraError())
		g.P("}")
		g.P("for {")
		g.P("msg, err := stream.Receive()")
		g.P("if err == ", ioEOF, " {")
		g.P("break")
		g.P("}")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("if err := clientStream.Send(msg); err != nil {")
		g.P("return nil, ", toZaraError())
		g.P("}")
		g.P("}")
		g.P("resp, err := clientStream.CloseAndRecv()")
		g.P("if err != nil {")
		g.P("return nil, ", toZaraError())
		g.P("}")
		g.P("return resp, nil")
		g.P("}")
		g.P()

	case "bidi":
		ioEOF := q(g, ioImport, "EOF")
		g.P("func ", recv, " ", method.GoName, "(ctx ", ctxType, ", stream ", sym(g, "BidiStream"), "[*", inType, ", *", outType, "]) error {")
		forwardHeaders()
		g.P("clientStream, err := g.client.", method.GoName, "(gctx)")
		g.P("if err != nil {")
		g.P("return ", toZaraError())
		g.P("}")
		g.P("errCh := make(chan error, 2)")
		g.P("go func() {")
		g.P("for {")
		g.P("msg, err := stream.Receive()")
		g.P("if err == ", ioEOF, " {")
		g.P("clientStream.CloseSend()")
		g.P("errCh <- nil")
		g.P("return")
		g.P("}")
		g.P("if err != nil {")
		g.P("errCh <- err")
		g.P("return")
		g.P("}")
		g.P("if err := clientStream.Send(msg); err != nil {")
		g.P("errCh <- ", toZaraError())
		g.P("return")
		g.P("}")
		g.P("}")
		g.P("}()")
		g.P("go func() {")
		g.P("for {")
		g.P("msg, err := clientStream.Recv()")
		g.P("if err == ", ioEOF, " {")
		g.P("errCh <- nil")
		g.P("return")
		g.P("}")
		g.P("if err != nil {")
		g.P("errCh <- ", toZaraError())
		g.P("return")
		g.P("}")
		g.P("if err := stream.Send(msg); err != nil {")
		g.P("errCh <- err")
		g.P("return")
		g.P("}")
		g.P("}")
		g.P("}()")
		g.P("var firstErr error")
		g.P("for i := 0; i < 2; i++ {")
		g.P("if err := <-errCh; err != nil && firstErr == nil {")
		g.P("firstErr = err")
		g.P("}")
		g.P("}")
		g.P("return firstErr")
		g.P("}")
		g.P()

	default: // unary
		g.P("func ", recv, " ", method.GoName, "(ctx ", ctxType, ", req *", inType, ") (*", outType, ", error) {")
		forwardHeaders()
		g.P("resp, err := g.client.", method.GoName, "(gctx, req)")
		g.P("if err != nil {")
		g.P("return nil, ", toZaraError())
		g.P("}")
		g.P("return resp, nil")
		g.P("}")
		g.P()
	}
}
