package main

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	codesImport        = protogen.GoImportPath("github.com/aldok10/zara-rpc/codes")
	statusImport       = protogen.GoImportPath("github.com/aldok10/zara-rpc/status")
	encodingImport     = protogen.GoImportPath("github.com/aldok10/zara-rpc/encoding")
	metadataImport     = protogen.GoImportPath("github.com/aldok10/zara-rpc/metadata")
	peerImport         = protogen.GoImportPath("github.com/aldok10/zara-rpc/peer")
	runtimeImport      = protogen.GoImportPath("github.com/aldok10/zara-rpc/runtime")
	kernelImport       = protogen.GoImportPath("github.com/aldok10/zara-rpc/kernel")
	routingImport      = protogen.GoImportPath("github.com/aldok10/zara-rpc/routing")
	clientImport       = protogen.GoImportPath("github.com/aldok10/zara-rpc/client")
	contextImport      = protogen.GoImportPath("context")
	httpImport         = protogen.GoImportPath("net/http")
	reflectImport      = protogen.GoImportPath("reflect")
	ioImport           = protogen.GoImportPath("io")
	grpcImport         = protogen.GoImportPath("google.golang.org/grpc")
	grpcMetadataImport = protogen.GoImportPath("google.golang.org/grpc/metadata")
	grpcStatusImport   = protogen.GoImportPath("google.golang.org/grpc/status")
	spbStatusImport    = protogen.GoImportPath("google.golang.org/genproto/googleapis/rpc/status")
	grpcbridgeImport   = protogen.GoImportPath("github.com/aldok10/zara-rpc/grpcbridge")
)

// q renders a qualified identifier and registers its import.
func q(g *protogen.GeneratedFile, path protogen.GoImportPath, name string) string {
	return g.QualifiedGoIdent(path.Ident(name))
}

// sym renders a framework symbol from its owning package. Framework-core
// symbols (Mux, Operation, Request, streams, interceptors, ...) live in
// runtime; cross-cutting symbols are emitted with a direct import of the
// subpackage that owns them (codes, status, encoding, metadata, peer,
// runtime, client).
func sym(g *protogen.GeneratedFile, name string) string {
	switch name {
	case "Code", "CodeOK", "CodeCanceled", "CodeUnknown", "CodeInvalidArgument",
		"CodeDeadlineExceeded", "CodeNotFound", "CodeAlreadyExists",
		"CodePermissionDenied", "CodeResourceExhausted", "CodeFailedPrecondition",
		"CodeAborted", "CodeOutOfRange", "CodeUnimplemented", "CodeInternal",
		"CodeUnavailable", "CodeDataLoss", "CodeUnauthenticated", "CodeFromString":
		return q(g, codesImport, name)
	case "NewError", "NewErrorf", "FromError", "FromHTTP", "FromGRPCStatus":
		return q(g, statusImport, name)
	case "Codec", "Decoder", "Encoder", "JSONCodec", "JSONV2Codec", "XMLCodec",
		"ProtoCodec", "ForName", "CodecForContentType", "CodecForRequest":
		return q(g, encodingImport, name)
	case "RequestMeta", "WithRequestMeta", "RequestMetaFromContext",
		"HeaderFromContext", "QueryFromContext", "BodyFromContext",
		"CookiesFromContext", "CookieFromContext", "HeaderPairs",
		"HeaderPairsFromMeta":
		return q(g, metadataImport, name)
	case "Peer", "WithPeer", "PeerFromContext":
		return q(g, peerImport, name)
	case "PathString", "PathBool", "PathInt32",
		"PathInt64", "PathUint32", "PathUint64", "PathFloat32", "PathFloat64",
		"PathBytes", "PathStringSlice", "PathInt64Slice":
		return q(g, runtimeImport, name)
	case "Mux":
		return q(g, routingImport, name)
	case "NewService", "Operation", "OperationBuilder":
		return q(g, kernelImport, name)
	case "ClientOption", "ClientBase", "NewClientBase", "WithCodec",
		"WithHTTPClient", "WithHeader", "ServerStreamTransport",
		"ServerStreamSSE", "ServerStreamWebSocket", "WithServerStreamTransport",
		"ServerStreamClient", "ClientStreamClient", "BidiStreamClient",
		"ServerStreamForClient", "ClientStreamForClient", "BidiStreamForClient",
		"DialWebSocket":
		return q(g, clientImport, name)
	default:
		return q(g, runtimeImport, name)
	}
}

// generateFile generates the zararpc registration code for a proto file.
func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + ".zararpc.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-zararpc. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-zararpc v0.1.0")
	g.P("// - protoc ", protocVersion(gen))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, svc := range file.Services {
		generateService(g, svc)
	}
}

// collectTags collects the custom struct tag overlay for a proto file.
//
// Oneof members are special: protobuf-go synthesizes a wrapper struct per
// member (Message_Field) holding the member's value, so a field-level tag
// on a oneof member targets that wrapper struct. The oneof_tags option
// targets the oneof field on the message struct itself.
func collectTags(file *protogen.File) tagOverlay {
	overlay := tagOverlay{}
	var collect func(msgs []*protogen.Message)
	collect = func(msgs []*protogen.Message) {
		for _, msg := range msgs {
			for _, field := range msg.Fields {
				tag := customTag(field)
				if tag == "" {
					continue
				}
				name := msg.GoIdent.GoName
				if field.Oneof != nil && !field.Desc.HasOptionalKeyword() {
					name = msg.GoIdent.GoName + "_" + field.GoName
				}
				if overlay[name] == nil {
					overlay[name] = map[string]string{}
				}
				overlay[name][field.GoName] = tag
			}
			for _, oneof := range msg.Oneofs {
				tag := oneofTag(oneof)
				if tag == "" {
					continue
				}
				// The oneof field on the message struct (e.g. OneOf).
				if overlay[msg.GoIdent.GoName] == nil {
					overlay[msg.GoIdent.GoName] = map[string]string{}
				}
				overlay[msg.GoIdent.GoName][oneof.GoName] = tag
			}
			collect(msg.Messages)
		}
	}
	collect(file.Messages)
	return overlay
}

// customTag returns the struct tag string declared on a field via the
// (zara.options.tags) field option, or "" when the field has none. The
// value is the full tag literal, e.g. `xml:"flag,attr" gorm:"primaryKey"`.
func customTag(field *protogen.Field) string {
	opts, ok := field.Desc.Options().(*descriptorpb.FieldOptions)
	if opts == nil || !ok {
		return ""
	}
	if !proto.HasExtension(opts, E_Tags) {
		return ""
	}
	tag, _ := proto.GetExtension(opts, E_Tags).(string)
	return tag
}

// oneofTag returns the struct tag string declared on a oneof via the
// (zara.options.oneof_tags) oneof option, or "" when the oneof has none.
func oneofTag(oneof *protogen.Oneof) string {
	opts, ok := oneof.Desc.Options().(*descriptorpb.OneofOptions)
	if opts == nil || !ok {
		return ""
	}
	if !proto.HasExtension(opts, E_OneofTags) {
		return ""
	}
	tag, _ := proto.GetExtension(opts, E_OneofTags).(string)
	return tag
}

// goString renders a string as a Go literal, preferring a raw string when
// the content has no backtick (struct tags usually qualify).
func goString(s string) string {
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}

func protocVersion(gen *protogen.Plugin) string {
	if v := gen.Request.GetCompilerVersion(); v != nil {
		return fmt.Sprintf("v%d.%d.%d", v.GetMajor(), v.GetMinor(), v.GetPatch())
	}
	return "(unknown)"
}

func strconvQuote(s string) string {
	return `"` + s + `"`
}

// generateService emits the handler interface, client interface, unimplemented type,
// request builders, and registration function for one service.
func generateService(g *protogen.GeneratedFile, svc *protogen.Service) {
	svcName := svc.GoName
	// Server handlers receive runtime.Ctx (transport metadata, codec,
	// protocol, payloads); the HTTP client keeps the caller's
	// context.Context.
	serverCtxType := q(g, runtimeImport, "Ctx")
	clientCtxType := q(g, contextImport, "Context")

	// ---- Handler interface ----
	g.P("// ", svcName, "Handler is the server implementation contract.")
	g.P("type ", svcName, "Handler interface {")
	for _, method := range svc.Methods {
		generateHandlerMethod(g, svcName, method, serverCtxType, false)
	}
	g.P("}")
	g.P()

	// ---- Unimplemented handler ----
	g.P("// Unimplemented", svcName, "Handler returns CodeUnimplemented for every method.")
	g.P("type Unimplemented", svcName, "Handler struct{}")
	g.P()
	for _, method := range svc.Methods {
		generateHandlerMethod(g, svcName, method, serverCtxType, true)
	}

	// ---- Request builders ----
	for _, method := range svc.Methods {
		rules, err := extractHTTPRules(method)
		if err != nil {
			panic(err)
		}
		for i, rule := range rules {
			generateRequestBuilder(g, svc, method, rule, i)
		}
	}

	// ---- Constants ----
	g.P("// Service and endpoint constants.")
	g.P("const (")
	g.P(svcName, "_FullName = ", strconvQuote(string(svc.Desc.FullName())))
	for _, method := range svc.Methods {
		g.P(rpcNameConstName(svcName, method.GoName), " = ", strconvQuote(method.GoName))
		rules, err := extractHTTPRules(method)
		if err != nil {
			panic(err)
		}
		for i, rule := range rules {
			g.P(pathConstName(svcName, method.GoName, i), " = ", strconvQuote(rule.path))
		}
	}
	g.P(")")
	g.P()

	// ---- Operation constructors ----
	for _, method := range svc.Methods {
		rules, err := extractHTTPRules(method)
		if err != nil {
			panic(err)
		}
		for i, rule := range rules {
			generateOperationFn(g, svc, method, rule, i)
		}
	}

	// ---- Registration function ----
	g.P("// Register", svcName, "Routes registers all HTTP endpoints of the service on the mux.")
	g.P("func Register", svcName, "Routes(mux *", sym(g, "Mux"), ", svc ", svcName, "Handler) error {")
	g.P("return mux.Register(")
	g.P(sym(g, "NewService"), "(")
	g.P(svcName, "_FullName,")
	for _, method := range svc.Methods {
		rules, err := extractHTTPRules(method)
		if err != nil {
			panic(err)
		}
		for i := range rules {
			g.P(operationFnName(svcName, method.GoName, i), "(svc),")
		}
	}
	g.P("))")
	g.P("}")
	g.P()

	g.P("// Register", svcName, "Handler registers the service on target (routing.Server, routing.Mux, or gRPC registrar).")
	g.P("func Register", svcName, "Handler(target any, svc ", svcName, "Handler) error {")
	g.P("if reg, ok := target.(interface{ Mux() *", sym(g, "Mux"), "; GRPC() any }); ok {")
	g.P("if err := Register", svcName, "Routes(reg.Mux(), svc); err != nil {")
	g.P("return err")
	g.P("}")
	g.P("if g := reg.GRPC(); g != nil {")
	g.P("Register", svcName, "Server(g, svc)")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P("if mux, ok := target.(*", sym(g, "Mux"), "); ok {")
	g.P("return Register", svcName, "Routes(mux, svc)")
	g.P("}")
	g.P("Register", svcName, "Server(target, svc)")
	g.P("return nil")
	g.P("}")
	g.P()

	// ---- Client interface and constructor ----
	generateClient(g, svc, clientCtxType)
}

// generateClient emits the client interface and constructor for a service.
func generateClient(g *protogen.GeneratedFile, svc *protogen.Service, ctxType string) {
	svcName := svc.GoName
	clientName := svcName + "HTTPClient"
	baseType := sym(g, "ClientBase")

	// ---- Client interface ----
	g.P("// ", clientName, " is a typed HTTP client for ", svcName, ".")
	g.P("type ", clientName, " interface {")
	for _, method := range svc.Methods {
		mode := streamMode(method)
		switch mode {
		case "server":
			g.P(method.GoName, "(", ctxType, ", *", g.QualifiedGoIdent(method.Input.GoIdent), ", ...", sym(g, "ClientOption"), ") (", sym(g, "ServerStreamForClient"), "[", g.QualifiedGoIdent(method.Output.GoIdent), "], error)")
		case "client":
			g.P(method.GoName, "(", ctxType, ", ...", sym(g, "ClientOption"), ") (", sym(g, "ClientStreamForClient"), "[", g.QualifiedGoIdent(method.Input.GoIdent), ", ", g.QualifiedGoIdent(method.Output.GoIdent), "], error)")
		case "bidi":
			g.P(method.GoName, "(", ctxType, ", ...", sym(g, "ClientOption"), ") (", sym(g, "BidiStreamForClient"), "[", g.QualifiedGoIdent(method.Input.GoIdent), ", ", g.QualifiedGoIdent(method.Output.GoIdent), "], error)")
		default:
			g.P(method.GoName, "(", ctxType, ", *", g.QualifiedGoIdent(method.Input.GoIdent), ", ...", sym(g, "ClientOption"), ") (*", g.QualifiedGoIdent(method.Output.GoIdent), ", error)")
		}
	}
	g.P()
	g.P("// Close releases any resources held by the client.")
	g.P("Close() error")
	g.P("}")
	g.P()

	// ---- Client struct ----
	g.P("type ", strings.ToLower(clientName[:1])+clientName[1:], " struct {")
	g.P(baseType)
	g.P("}")
	g.P()

	// ---- NewClient constructor ----
	g.P("// New", clientName, " creates a new ", clientName, " that calls the given base URL.")
	g.P("func New", clientName, "(baseURL string, opts ...", sym(g, "ClientOption"), ") ", clientName, " {")
	g.P("return &", strings.ToLower(clientName[:1])+clientName[1:], "{ClientBase: ", sym(g, "NewClientBase"), "(baseURL, opts...)}")
	g.P("}")
	g.P()

	// ---- Client method implementations ----
	for _, method := range svc.Methods {
		mode := streamMode(method)
		methodName := method.GoName
		inType := g.QualifiedGoIdent(method.Input.GoIdent)
		outType := g.QualifiedGoIdent(method.Output.GoIdent)
		rule := firstHTTPRule(method)
		recv := "c *" + strings.ToLower(clientName[:1]) + clientName[1:]

		switch mode {
		case "server":
			reflectTypeOf := q(g, reflectImport, "TypeOf")
			g.P("func (", recv, ") ", methodName, "(ctx ", ctxType, ", req *", inType, ", extraOpts ...", sym(g, "ClientOption"), ") (", sym(g, "ServerStreamForClient"), "[", outType, "], error) {")
			g.P("raw, err := c.DoServerStream(ctx, ", httpMethodConst(g, rule.method), ", ", pathConstName(svc.GoName, method.GoName, 0), ", req, ", reflectTypeOf, "((*", outType, ")(nil)).Elem(), extraOpts...)")
			g.P("if err != nil {")
			g.P("return ", sym(g, "ServerStreamForClient"), "[", outType, "]{}, err")
			g.P("}")
			g.P("return ", sym(g, "ServerStreamForClient"), "[", outType, "]{Inner: raw}, nil")
			g.P("}")
			g.P()

		case "client":
			reflectTypeOf := q(g, reflectImport, "TypeOf")
			g.P("func (", recv, ") ", methodName, "(ctx ", ctxType, ", extraOpts ...", sym(g, "ClientOption"), ") (", sym(g, "ClientStreamForClient"), "[", inType, ", ", outType, "], error) {")
			g.P("raw, err := c.DoClientStream(ctx, ", httpMethodConst(g, rule.method), ", ", pathConstName(svc.GoName, method.GoName, 0), ", ", reflectTypeOf, "((*", outType, ")(nil)).Elem(), extraOpts...)")
			g.P("if err != nil {")
			g.P("return ", sym(g, "ClientStreamForClient"), "[", inType, ", ", outType, "]{}, err")
			g.P("}")
			g.P("return ", sym(g, "ClientStreamForClient"), "[", inType, ", ", outType, "]{Inner: raw}, nil")
			g.P("}")
			g.P()

		case "bidi":
			reflectTypeOf := q(g, reflectImport, "TypeOf")
			g.P("func (", recv, ") ", methodName, "(ctx ", ctxType, ", extraOpts ...", sym(g, "ClientOption"), ") (", sym(g, "BidiStreamForClient"), "[", inType, ", ", outType, "], error) {")
			g.P("raw, err := c.DoBidiStream(ctx, ", pathConstName(svc.GoName, method.GoName, 0), ", ", reflectTypeOf, "((*", inType, ")(nil)).Elem(), extraOpts...)")
			g.P("if err != nil {")
			g.P("return ", sym(g, "BidiStreamForClient"), "[", inType, ", ", outType, "]{}, err")
			g.P("}")
			g.P("return ", sym(g, "BidiStreamForClient"), "[", inType, ", ", outType, "]{Inner: raw}, nil")
			g.P("}")
			g.P()

		default: // unary
			g.P("func (", recv, ") ", methodName, "(ctx ", ctxType, ", req *", inType, ", extraOpts ...", sym(g, "ClientOption"), ") (*", outType, ", error) {")
			g.P("resp := &", outType, "{}")
			g.P("err := c.DoUnary(ctx, ", httpMethodConst(g, rule.method), ", ", pathConstName(svc.GoName, method.GoName, 0), ", ", strconvQuote(rule.body), ", req, resp, extraOpts...)")
			g.P("if err != nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("return resp, nil")
			g.P("}")
			g.P()
		}
	}

	// ---- Close method ----
	g.P("func (c *", strings.ToLower(clientName[:1])+clientName[1:], ") Close() error {")
	g.P("return nil")
	g.P("}")
	g.P()
}
