// gRPC server registration and client stub emission.
//
// The gRPC server contract is the SAME XxxServiceHandler interface used by
// the HTTP routes (handlers receive runtime.Ctx), so one implementation
// serves both transports — no hand-written adapter is needed for
// registration or for preparing runtime.Ctx. The generated method handlers
// convert the incoming gRPC context/metadata into runtime.Ctx and convert
// zararpc errors back to gRPC status errors via the framework's grpcbridge
// package (github.com/aldok10/zara-rpc/grpcbridge), so the generated output
// stays thin — no per-package bridge is emitted.
package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateGRPCFile emits the gRPC server registration and client stubs for
// a proto file. The client stubs are grpc-go compatible so the generated
// gateway (REST -> gRPC) can call them.
func generateGRPCFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + ".grpc.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-zararpc. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-zararpc v0.1.0")
	g.P("// - protoc ", protocVersion(gen))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, svc := range file.Services {
		generateGRPCService(g, svc, file)
	}
}

// generateGRPCService emits the client stubs, ServiceDesc, method handlers,
// and RegisterXxxServiceServer for one service.
func generateGRPCService(g *protogen.GeneratedFile, svc *protogen.Service, file *protogen.File) {
	svcName := svc.GoName
	clientName := svcName + "Client"
	lowerClient := strings.ToLower(clientName[:1]) + clientName[1:]
	ctxType := q(g, contextImport, "Context")
	grpcCallOption := q(g, grpcImport, "CallOption")
	grpcStaticMethod := q(g, grpcImport, "StaticMethod")
	grpcClientConn := q(g, grpcImport, "ClientConnInterface")
	fullName := string(svc.Desc.FullName())

	// ---- FullMethodName constants ----
	g.P("// FullMethodName constants for the service.")
	g.P("const (")
	for _, method := range svc.Methods {
		g.P(svcName, "_", method.GoName, "_FullMethodName = ", strconvQuote("/"+fullName+"/"+method.GoName))
	}
	g.P(")")
	g.P()

	// ---- Client interface ----
	g.P("// ", clientName, " is the client API for ", svcName, ".")
	g.P("type ", clientName, " interface {")
	for _, method := range svc.Methods {
		mode := streamMode(method)
		inType := g.QualifiedGoIdent(method.Input.GoIdent)
		outType := g.QualifiedGoIdent(method.Output.GoIdent)
		switch mode {
		case "server":
			g.P(method.GoName, "(ctx ", ctxType, ", in *", inType, ", opts ...", grpcCallOption, ") (", q(g, grpcImport, "ServerStreamingClient"), "[", outType, "], error)")
		case "client":
			g.P(method.GoName, "(ctx ", ctxType, ", opts ...", grpcCallOption, ") (", q(g, grpcImport, "ClientStreamingClient"), "[", inType, ", ", outType, "], error)")
		case "bidi":
			g.P(method.GoName, "(ctx ", ctxType, ", opts ...", grpcCallOption, ") (", q(g, grpcImport, "BidiStreamingClient"), "[", inType, ", ", outType, "], error)")
		default:
			g.P(method.GoName, "(ctx ", ctxType, ", in *", inType, ", opts ...", grpcCallOption, ") (*", outType, ", error)")
		}
	}
	g.P("}")
	g.P()

	// ---- Client struct + constructor ----
	g.P("type ", lowerClient, " struct {")
	g.P("cc ", grpcClientConn)
	g.P("}")
	g.P()
	g.P("func New", clientName, "(cc ", grpcClientConn, ") ", clientName, " {")
	g.P("return &", lowerClient, "{cc}")
	g.P("}")
	g.P()

	// ---- Client method implementations ----
	streamIdx := 0
	for _, method := range svc.Methods {
		mode := streamMode(method)
		inType := g.QualifiedGoIdent(method.Input.GoIdent)
		outType := g.QualifiedGoIdent(method.Output.GoIdent)
		fullMethod := svcName + "_" + method.GoName + "_FullMethodName"

		switch mode {
		case "server":
			g.P("func (c *", lowerClient, ") ", method.GoName, "(ctx ", ctxType, ", in *", inType, ", opts ...", grpcCallOption, ") (", q(g, grpcImport, "ServerStreamingClient"), "[", outType, "], error) {")
			g.P("cOpts := append([]", grpcCallOption, "{", grpcStaticMethod, "()}, opts...)")
			g.P("stream, err := c.cc.NewStream(ctx, &", svcName, "_ServiceDesc.Streams[", streamIdx, "], ", fullMethod, ", cOpts...)")
			g.P("if err != nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("x := &", q(g, grpcImport, "GenericClientStream"), "[", inType, ", ", outType, "]{ClientStream: stream}")
			g.P("if err := x.ClientStream.SendMsg(in); err != nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("if err := x.ClientStream.CloseSend(); err != nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("return x, nil")
			g.P("}")
			g.P()
			streamIdx++

		case "client":
			g.P("func (c *", lowerClient, ") ", method.GoName, "(ctx ", ctxType, ", opts ...", grpcCallOption, ") (", q(g, grpcImport, "ClientStreamingClient"), "[", inType, ", ", outType, "], error) {")
			g.P("cOpts := append([]", grpcCallOption, "{", grpcStaticMethod, "()}, opts...)")
			g.P("stream, err := c.cc.NewStream(ctx, &", svcName, "_ServiceDesc.Streams[", streamIdx, "], ", fullMethod, ", cOpts...)")
			g.P("if err != nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("x := &", q(g, grpcImport, "GenericClientStream"), "[", inType, ", ", outType, "]{ClientStream: stream}")
			g.P("return x, nil")
			g.P("}")
			g.P()
			streamIdx++

		case "bidi":
			g.P("func (c *", lowerClient, ") ", method.GoName, "(ctx ", ctxType, ", opts ...", grpcCallOption, ") (", q(g, grpcImport, "BidiStreamingClient"), "[", inType, ", ", outType, "], error) {")
			g.P("cOpts := append([]", grpcCallOption, "{", grpcStaticMethod, "()}, opts...)")
			g.P("stream, err := c.cc.NewStream(ctx, &", svcName, "_ServiceDesc.Streams[", streamIdx, "], ", fullMethod, ", cOpts...)")
			g.P("if err != nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("x := &", q(g, grpcImport, "GenericClientStream"), "[", inType, ", ", outType, "]{ClientStream: stream}")
			g.P("return x, nil")
			g.P("}")
			g.P()
			streamIdx++

		default: // unary
			g.P("func (c *", lowerClient, ") ", method.GoName, "(ctx ", ctxType, ", in *", inType, ", opts ...", grpcCallOption, ") (*", outType, ", error) {")
			g.P("cOpts := append([]", grpcCallOption, "{", grpcStaticMethod, "()}, opts...)")
			g.P("out := new(", outType, ")")
			g.P("err := c.cc.Invoke(ctx, ", fullMethod, ", in, out, cOpts...)")
			g.P("if err != nil {")
			g.P("return nil, err")
			g.P("}")
			g.P("return out, nil")
			g.P("}")
			g.P()
		}
	}

	// ---- ServiceDesc ----
	g.P("// ", svcName, "_ServiceDesc is the grpc.ServiceDesc for ", svcName, ".")
	g.P("var ", svcName, "_ServiceDesc = ", q(g, grpcImport, "ServiceDesc"), "{")
	g.P("ServiceName: ", strconvQuote(fullName), ",")
	g.P("HandlerType: (*", svcName, "Handler)(nil),")
	g.P("Methods: []", q(g, grpcImport, "MethodDesc"), "{")
	for _, method := range svc.Methods {
		if streamMode(method) != "unary" {
			continue
		}
		g.P("{MethodName: ", strconvQuote(method.GoName), ", Handler: _", svcName, "_", method.GoName, "_Handler},")
	}
	g.P("},")
	g.P("Streams: []", q(g, grpcImport, "StreamDesc"), "{")
	for _, method := range svc.Methods {
		mode := streamMode(method)
		if mode == "unary" {
			continue
		}
		desc := "{StreamName: " + strconvQuote(method.GoName) + ", Handler: _" + svcName + "_" + method.GoName + "_Handler"
		switch mode {
		case "server":
			desc += ", ServerStreams: true"
		case "client":
			desc += ", ClientStreams: true"
		default:
			desc += ", ServerStreams: true, ClientStreams: true"
		}
		g.P(desc, "},")
	}
	g.P("},")
	g.P("Metadata: ", strconvQuote(file.Desc.Path()), ",")
	g.P("}")
	g.P()

	// ---- Method handlers ----
	for _, method := range svc.Methods {
		generateGRPCMethodHandler(g, svc, method)
	}

	// ---- Register ----
	g.P("// Register", svcName, "Server registers the service on a ", q(g, grpcImport, "ServiceRegistrar"), " or any target implementing RegisterService.")
	g.P("// Handlers receive runtime.Ctx (the same contract as the HTTP routes),")
	g.P("// so one implementation serves both transports.")
	g.P("func Register", svcName, "Server(s any, svc ", svcName, "Handler) {")
	g.P("if reg, ok := s.(", q(g, grpcImport, "ServiceRegistrar"), "); ok {")
	g.P("reg.RegisterService(&", svcName, "_ServiceDesc, svc)")
	g.P("}")
	g.P("}")
	g.P()
}

// generateGRPCMethodHandler emits the grpc-go method handler for one
// method. The handler decodes the request, converts the gRPC context into
// runtime.Ctx (grpcbridge.CtxFor), calls the XxxServiceHandler method
// (which receives runtime.Ctx), and converts zararpc errors back to gRPC
// status errors (grpcbridge.ToGRPC).
func generateGRPCMethodHandler(g *protogen.GeneratedFile, svc *protogen.Service, method *protogen.Method) {
	svcName := svc.GoName
	handlerName := "_" + svcName + "_" + method.GoName + "_Handler"
	fullMethod := svcName + "_" + method.GoName + "_FullMethodName"
	inType := g.QualifiedGoIdent(method.Input.GoIdent)
	outType := g.QualifiedGoIdent(method.Output.GoIdent)
	ctxType := q(g, contextImport, "Context")
	grpcServerStream := q(g, grpcImport, "ServerStream")
	handlerIface := svcName + "Handler"
	ctxFor := q(g, grpcbridgeImport, "CtxFor")
	toGRPC := q(g, grpcbridgeImport, "ToGRPC")

	switch streamMode(method) {
	case "server":
		g.P("func ", handlerName, "(srv any, stream ", grpcServerStream, ") error {")
		g.P("m := new(", inType, ")")
		g.P("if err := stream.RecvMsg(m); err != nil {")
		g.P("return err")
		g.P("}")
		g.P("if err := srv.(", handlerIface, ").", method.GoName, "(", ctxFor, "(stream.Context(), ", fullMethod, "), m, &", q(g, grpcbridgeImport, "ServerStreamAdapter"), "[", outType, "]{Stream: stream}); err != nil {")
		g.P("return ", toGRPC, "(err)")
		g.P("}")
		g.P("return nil")
		g.P("}")
		g.P()

	case "client":
		g.P("func ", handlerName, "(srv any, stream ", grpcServerStream, ") error {")
		g.P("resp, err := srv.(", handlerIface, ").", method.GoName, "(", ctxFor, "(stream.Context(), ", fullMethod, "), &", q(g, grpcbridgeImport, "ClientStreamAdapter"), "[", inType, "]{Stream: stream})")
		g.P("if err != nil {")
		g.P("return ", toGRPC, "(err)")
		g.P("}")
		g.P("return stream.SendMsg(resp)")
		g.P("}")
		g.P()

	case "bidi":
		g.P("func ", handlerName, "(srv any, stream ", grpcServerStream, ") error {")
		g.P("if err := srv.(", handlerIface, ").", method.GoName, "(", ctxFor, "(stream.Context(), ", fullMethod, "), &", q(g, grpcbridgeImport, "BidiStreamAdapter"), "[", inType, ", ", outType, "]{Stream: stream}); err != nil {")
		g.P("return ", toGRPC, "(err)")
		g.P("}")
		g.P("return nil")
		g.P("}")
		g.P()

	default: // unary
		grpcUnaryInfo := q(g, grpcImport, "UnaryServerInfo")
		grpcUnaryInterceptor := q(g, grpcImport, "UnaryServerInterceptor")
		g.P("func ", handlerName, "(srv any, ctx ", ctxType, ", dec func(any) error, interceptor ", grpcUnaryInterceptor, ") (any, error) {")
		g.P("in := new(", inType, ")")
		g.P("if err := dec(in); err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("if interceptor == nil {")
		g.P("resp, err := srv.(", handlerIface, ").", method.GoName, "(", ctxFor, "(ctx, ", fullMethod, "), in)")
		g.P("if err != nil {")
		g.P("return nil, ", toGRPC, "(err)")
		g.P("}")
		g.P("return resp, nil")
		g.P("}")
		g.P("info := &", grpcUnaryInfo, "{Server: srv, FullMethod: ", fullMethod, "}")
		g.P("handler := func(ctx ", ctxType, ", req any) (any, error) {")
		g.P("resp, err := srv.(", handlerIface, ").", method.GoName, "(", ctxFor, "(ctx, ", fullMethod, "), req.(*", inType, "))")
		g.P("if err != nil {")
		g.P("return nil, ", toGRPC, "(err)")
		g.P("}")
		g.P("return resp, nil")
		g.P("}")
		g.P("return interceptor(ctx, in, info, handler)")
		g.P("}")
		g.P()
	}
}